modLoader = "javafml"
loaderVersion = "[54,)"
license = "MIT"

issueTrackerURL = "https://github.com/dodoflix/DisableVillagerTrade/issues"

[[mods]]
modId = "disablevillagertrade"
version = "${version}"
displayName = "DisableVillagerTrade"
displayURL = "https://github.com/dodoflix/DisableVillagerTrade"
logoFile = "logo.png"
credits = "dodo"
authors = "dodo"
description = '''
A lightweight mod to prevent players from trading with villagers.
Configurable with permission bypass and world exclusions.
'''

[[dependencies.disablevillagertrade]]
modId = "forge"
type = "required"
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.disablevillagertrade]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
